export const drikkeTurRules = [
                'Hvem har finest smil?',
                'Hvem promper mest?',
                'Hvem danser best?',
                'Hvem har finest klesstil i kveld?',
                'Hvem i dette rommet ville vært en Disney prinsesse?',
                'Hvem gifter seg først?',
                'Hvem har oftest sex?',
                'Hvem er mest slask?',
                'Hvem er løsest?',
                'Hvem får først barn?',
                'Hvem er mest sannsynlig til å fa med noen hjem i kveld?',
                'Hvem kysser best?',
                'Hvem synger falskest?',
                'Hvem er morsomst?',
                'Hvem er mest sannsynlig til å bruke opp alt stipendet eller lønna?',
                'Hvem er størst drama queen?',
                'Hvem er den største løgneren?',
                'Hvem er den største pingla?',
                'Hvem er den største våghalsen?',
                'Hvem er mest romantisk?',
                'Hvem er best i senga?',
                'Hvem er mest tøffel de andre? ',
                'Hvem kjører oftest over fartsgrensa?',
                'Hvem er bedreviteren?',
                'Hvem hadde overlevd på en øde øy?',
                'Hvem er mest sporty?',
                'Hvem har spydd i fylla?',
                'Hvem dør først i en skrekkfilm',
                'Hvem har hatt mest sex i utlandet?',
                'Hvem har flest tatoveringer?',
                'Hvem har vært på glattcella?',
                'Hvem har kastet opp på noen?',
                'Hvem er mest sannsynlig for å ha tisset offentlig?',
                'Hvem er mest positiv?',
                'Hvem popper flest kviser?',
                'Hvem er mest sannsynlig til å rømme hjemmefra?',
                'Hvem har blitt pumpa?',
                'Hvem har hatt flest sexpartnere i løpet av en kveld?',
                'Hvem har spist et insekt?',
                'Hvem er den største playeren?',
                'Hvem har begått flest lovbrudd?',
                'Hvem blir fortest forelska?',
                'Hvem har sendt nakenbilde?',
                'Hvem har sett flest Disneyfilmer?',
                'Hvem har hatt flest kjønnssykdommer?',
                'Hvem er mest sannsynlig til å bli pornostjerne?',
                'Hvem har hatt trekant?',
                'Hvem har ligget med en fra samme kjønn?',
                'Hvem er mest ubesluttsom?',
                'Hvem har prøvd narkotika?',
                'Hvem har hatt sex med flest eldre?',
                'Hvem har hatt sex med flest yngre?',
                'Hvem spiser mest?',
                'Hvem er mest sannsynlig til å være med i Paradise Hotel?',
                'Hvem har vært i flest land?',
                'Hvem er mest sannsynlig til å være utro?',
                'Hvem får kjæreste i løpet av året?',
                'Hvem er mest avhengig av sosiale medier? ',
                'Hvem er mest sannsynlig til å begå et drap? ',
                'Hvem er mest sannsynlig til å stryke i studiet?',
                'Hvem stjeler flest drinker på byen? ',
                'Hvem velger sex over vennene?',
                'Hvem er festens midtpunkt?',
                'Hvem synger i dusjen?',
                'Hvem er den største stalkeren?',
                'Hvem har den beste latteren?',
                'Hvem har vært i flest slåsskamper?',
                'Hvem er den største flørteren?',
                'Hvem har den diggeste rumpa?',
                'Hvem er mest guttegal/jentegal?',
                'Hvem er den største pervoen?',
                'Hvem er den beste stripperen?',
                'Hvem har de diggeste puppene?',
                'Hvem har det fineste håret?',
                'Hvem er mest sannsynlig til å skifte legning? ',
                'Hvem bryr seg mest om utseendet?',
                'Hvem er golddigger?',
                'Hvem er størst wannabe?',
                'Hvem driter seg oftest ut?',
                'Hvem er høylytt i senga?',
                'Hvem har de diggeste leppene?',
                'Hvem er den største alkoholikeren?',
                'Hvem ville du hooket med i dette rommet?',
                'Hvem er mest sannsynlig til å hooke med en kjendis?',
                'Hvem i dette rommet ville vært en Disney prinsesse? ',
                'Hvem ville blitt ringt opp av ex on the beach fordi eksen hadde meldt seg på?',
                'Hvem er mest sannsynlig til å lykkes i livet?',
                'Hvem er mest sannsynlig til å binge watche Netflix?',
                'Hvem ser på mest porno?',
                'Hvem hadde vært den beste skurken',
                'Hvem er best i senga',
                'Hvem drikker alltid den beste alkoholen på fest?',
                'Hvem blir rikest?',
                'Hvem er mest sassy?',
                'Hvem kunne hatt en suggar daddy?',
                'Hvem kunne hatt en cougar?',
                'Hvem liker best 69?',
                'Hvem vinner «vil du bli millionær»?',
                'Hvem vinner «mesternes mester»?',
                'Hvem er mest med familien sin?',
                'Hvem er den største dyreelskeren?',
                'Hvem ville vunnet i poker?',
                'Hvem gir den beste blow joben/ slikkinga?',
                'Hvem ville du hatt med deg på en øde øy?',
                'Hvem kunne blitt president?',
                'Hvem gifter seg først?',
                'Hvem er den flinkeste kokken?',
                'Hvem ville først blitt svindla?',
                'Hvem kunne begått det beste og mest utspekulerte mordet?',
                'Hvem vinner flest krangler/diskusjoner?',
                'Hvem tiltrekker seg mest sære og rare gutter/jenter?',
                'Hvem benker mest? ',
                'Hvem har minst føtter? ',
                'Hvem har størst føtter? ',
                'Hvem er flinkest til å ri?',
                'Hvem jobber mest under sex?',
                'Hvem er flinkest i kriser?',
                'Hvem er flinkest med penger?',
                'Hvem snakker mest i sosiale lag? ',
                'Hvem mister først passet sitt?',
                'Hvem dør først? ',
                'Hvem har det fineste bryllupet?',
                'Hvem kaster klærne først på fest? ',
                'Hvem vinner mest i Stein saks papir? ',
                'Hvem har prøvd flest rusmidler?',
                'Hvem er mest lettrørt? ',
                'Hvem har sloss mest? ',
                'Hvem er den med best humor? ',
                'Hvem er den mest uskyldige?',
                'Hvem bruker mest penger på klær? ',
                'Hvem er den største lurmusen? ',
                'Hvem er mest hard to Get? ',
                'Hvem har den diggeste moren? ',
                'Hvem har den kjekkeste faren?',
                'Hvem er flinkest i språk? ',
                'Hvem har best stil? ',
                'Hvem er best på å shotte? ',
                'Hvem er best på å shugge? ',
                'Hvem har best smak i gutter/jenter/mest lik din?',
                'Hvem har den rareste smaken i gutter/jenter?',
                'Hvem lukter alltid best? ',
                'Hvem har den største garderoben? ',
                'Hvem blir mest sjalu? ',
                'Hvem er den hissigste?',
                'Hvem har forandret seg mest? ',
                'Hvem gjør minst men får mest ut av det? ',
                'Hvem virker mest uskyldig, men er mest kinky?',
                'Hvem er den beste samtalepartneren? ',
                'Hvem ville du hatt trekant med?',
                'Hvem er gøyest på byen? ',
                'Hvem har brukt mest penger på materielle ting gjennom livet? ',
                'Hvem er mest klumsete? ',
                'Hvem er mest romantisk? ',
                'Hvem har mest pågangsmot? ',
                'Hvem er best på barneoppdragelse? ',
                'Hvem tåler mest psykisk? ',
                'Hvem tåler mest smerte? ',
                'Hvem er mest avhengig av sex?',
                'Hvem er mest moody? ',
                'Hvem ligner mest på foreldrene sine?',
                'Hvem er best til å forklare? ',
                'Hvem har best danse moves?',
                'Hvem har finest pupper?',
                'Hvem er kjekkest?',
                'Hvem er mest glad i å sove?',
                'Hvem er backer deg alltid og holder ryggen din i en krangel?',
                'Hvem liker å kveles?',
                'Hvem er bolest?',
                'Hvem har vert innom den største penisen?',
                'Hvem har finest rompe',
                'Hvem konsumerer mest drikke?',
                'Hvem er best til å danse',
                'Hvem kommer først?',
                'Hvem har finest lår?',
                'Hvem er oftest syk?',
                'Hvem bruker mest penger på byen?',
                'Hvem tar noen med seg hjem i kveld?',
                'Hvem kunne ønske de forsatt var russ?',
                'Hvem mistet først sin jomfrudom?',
                'Hvem har flest sex leker?',
                'Hvem stønner høyest?',
                'Hvem er er kåtest?',
                'Hvem har mest hår??',
                'Hvem hadde planlagt en kjønnsoperasjon',
                'Hvem er mest renslig',
                'Hvem er den største nerden?',
                'Hvem er den største råneren?',
                'Hvem har oftest ølbriller?',
                'Hvem ender opp på NAV?',
                ]


    
    
    

    