export const jegHarAldriGrovRules= [
    'Jeg har aldri hatt trekant',
    'Jeg har aldri hatt analsex',
    'Jeg har aldri vert utro',
    'Jeg har aldri blitt fersket',
    'Jeg har aldri onanert offentlig',
    'Jeg har aldri hatt sex offentlig',
    'Jeg har aldri hatt sex på en trampoline',
    'Jeg har aldri hatt sex i foreldrene mines seng',
    'Jeg har aldri kjørt brannbil',
    'Jeg har aldri revnet strengen',
    'Jeg har aldri hatt sex på en båt',
    'Jeg har aldri hatt sex i en bil',
    'Jeg har aldri brukt en gloryhole',
    'Jeg har aldri hatt sex i uniform',
    'Jeg har aldri smakt på mine egne væsker',
    'Jeg har aldri hatt sex med en gutt',
    'Jeg har aldri hatt sex med en jente',
    'Jeg har aldri blitt rimmet',
    'Jeg har aldri rimmet noen',
    'Jeg har aldri hatt sex med mer en to forskjellige iløpet av 24t',
    'Jeg har aldri hatt sex på en festival',
    'Jeg har aldri prøvd bondage',
    'Jeg har aldri hatt fler en 5 orgasmer iløpet av 24t',
    'Jeg har aldri disiplin i sex',
    'Jeg har aldri tatt den store BDSM testen',
    'Jeg har aldri hatt en One night stand',
    'Jeg har aldri fantasert om læreren',
    'Jeg har aldri brukt sexleketøy på noen',
    'Jeg har aldri brukt sex for egen vinnning',
    'Jeg har aldri hatt sex for penger',
    'Jeg har aldri sniktittet på noen som har hatt sex',
    'Jeg har aldri fersket noen i å ha sex',
    'Jeg har aldri hatt sex med tilskuere',
    'Jeg har aldri onanert på kamera',
    'Jeg har aldri hatt sex på skolen',
    'Jeg har aldri laget en sex video',
    'Jeg har aldri gjort noe sexuelt med noen på kino',
    'Jeg har aldri tatt psykadelika',
    'Jeg har aldri tatt kokain',
    'Jeg har aldri prøvd amfetamin',
    'Jeg har aldri kjørt i fylla',
    'Jeg har aldri hatt sex men en venns kjæreste',
    'Jeg har aldri hatt sex på soffaen til en venn',
    'Jeg har aldri brukt en frukt som sex leketøy',
    'Jeg har aldri kvelt et annen iløpet av sex',
    'Jeg har aldri kjøpt narkotika',
    'Jeg har aldri solgt narkotika',
    'Jeg har aldri fistet noen',
    'Jeg har aldri ødelagt et møbel mens jeg har hatt sex',
    'Jeg har aldri kjøpt et sex leketøy til noen',
    'Jeg har aldri hatt sex på et offentlig toalett',
    'Jeg har aldri hatt sex på et tog',
    'Jeg har aldri vert på et sex-ebition',
    'Jeg har aldri juget for å få meg noe',
    'Jeg har aldri hatt sex utendørs',
    'Jeg har aldri hatt sex i skogen',
    'Jeg har aldri dratt lengre en 2t for å ha sex med noen',
    'Jeg har aldri hatt sex med noen av mine venners foreldre',
    'Jeg har aldri hatt sex med en ste-søster/bror',
    'Jeg har aldri sett på porno offentlig',
    'Jeg har aldri onanert til gore-porn',
    'Jeg har aldri sett 2 girls 1 cup',
    'Jeg har aldri sett pain olympics',
    'Jeg har aldri sett one man one jar',
    'Jeg har aldri sett Kim Kardashians sex video',
    'Jeg har aldri sett noen jeg kjenner på en porno nettside',
    'Jeg har aldri hatt sex med noen som er over 10 år eldre en meg',
    'Jeg har aldri hatt sex med noen som er under 10 år yngre en meg',
    'Jeg har aldri hatt sex med en russ',
    'Jeg har aldri vert med på en orgie',
    'Jeg har aldri hatt en firkant',
    'Jeg har aldri fantasert seksuelt om noen i familien min',
    'Jeg har aldri hatt sex i en fornølyelsespark',
    'Jeg har aldri gitt noen en kjønnsykdom',
    'Jeg har aldri hatt en kjønnsykdom',
    'Jeg har aldri vert på helsestasjonen',
    'Jeg har aldri blitt kastet ut hos en One night stand',
    'Jeg har aldri hatt en walk-of-shame',
    'Jeg har aldri hatt sex før ekteskapet',
    'Jeg har aldri fått noen til å squirte, eller gjort det selv',
    'Jeg har aldri hatt sex på et utested',
    'Jeg har aldri holdt på med noen fordi de har penger',
    'Jeg har aldri kommet tidlig når jeg har hatt sex',
    'Jeg har aldri onanert til facebook bilder an noen',
    'Jeg har aldri stalket noen på sosiale medier',
    'Jeg har aldri pisket meg selv',
    'Jeg har aldri puttet sperm i sjampoflasken til en venn',
    'Jeg har aldri ødelagt doen til noen',
    'Jeg har aldri dopet drinken til noen',
    'Jeg har aldri prøvd hasj brownies',
    'Jeg har aldri hatt sex med noen som er for fulle',
    'Jeg har aldri glemt navnet til den jeg hadde sex med',
    'Jeg har aldri hatt sex med noen jeg ikke kunne navnet på',
    'Jeg har aldri prompet under sex',
    'Jeg har aldri hatt sex uten kondom',
    'Jeg har aldri hatt sex med noen i klassen eller jobb',
    'Jeg har aldri blitt skuffet over en gutts penis størrelse',
    'Jeg har aldri blitt skuffet over en jentes pupper',
    'Jeg har aldri onanert til undertøys kataloger',
    'Jeg har aldri betalt for porno',
    'Jeg har aldri juget om å ha sex med noen',
    'Jeg har aldri sendt et one night stand hjem',
]