export const jegHarAldriMildRules= [
    'Jeg har alltid våknet, og vet hvor jeg er',
    'Jeg har aldri hoppa fra 3-metern',
    'Jeg har aldri dratt på skolen uten å spise frokost',
    'Jeg har aldri strøket i et fag',
    'Jeg har aldri fått mer enn 2 timer fravær',
    'Jeg har aldri spist lutefisk',
    'Jeg har aldri vært i Danmark',
    'Jeg har aldri sitti i avhør på politistasjon',
    'Jeg har aldri blitt kalt inn til rektor',
    'Jeg har aldri skutt noe før',
    'Jeg har aldri vært i "syden"',
    'Jeg har aldri vært i Amerika',
    'Jeg har aldri vært i asia',
    'Jeg har aldri malt et hus',
    'Jeg har aldri vært på tv',
    'Jeg har aldri brukt noe form for narkotisk stoff',
    'Jeg har aldri vært naken på et offentlig sted',
    'Jeg har aldri skada noen hardt',
    'Jeg har aldri svømt mens jeg har vært full',
    'Jeg har aldri vært lenger under vann enn 3 meter',
    'Jeg har aldri hoppet gjenom eit vindu',
    'Jeg har aldri kjørt bil/sykkel i over 200km/t',
    'Jeg har aldri hatt sex',
    'Jeg har aldri hoppet ut fra høyere enn 15m ned i vann',
    'Jeg har aldri vært utenfor europa',
    'Jeg har aldri hatt hull i tennene',
    'Jeg har aldri brukket et ben',
    'Jeg har aldri hoppet i fallskjerm',
    'Jeg har aldri hatt dårligare enn 4 i eit fag det siste året',
    'Jeg har aldri vært på legevakten',
    'Jeg har aldri sloss med andre enn fetteren min',
    'Jeg har aldri drukket Baileys',
    'Jeg har aldri eid en bil',
    'Jeg har aldri vert "hangover" dagen derpå',
    'Jeg har aldri vegd meir enn 75 kilo',
    'Jeg har aldri fått en 6er på skolen',
    'Jeg har aldri hatt en kjæreste',
    'Jeg har aldri nytet en kopp kaffe, verken med eller uten sprit i.',
    'Jeg har aldri blitt satt i fyllearresten',
    'Jeg har aldri vært full',
    'Jeg har aldri vært på Ikea',
    'Jeg har aldri kræsjet en bil',
    'Jeg har aldri stått på henda oppe på et fjell',
    'Jeg har aldri kysset en gutt',
    'Jeg har aldri kysset en jente',
    'Jeg har aldri spist lungemos',
    'Jeg har aldri røykt hasj',
    'Jeg har aldri smakt brunost',
    'Jeg har aldri spist fisk',
    'Jeg har aldri likt oliven',
    'Jeg har aldri prøvd bungiejump',
    'Jeg har aldri røyka',
    'Jeg har aldri kjørt ATV',
    'Jeg har aldri besvimt',
    'Jeg har aldri drukket noe sterkere enn whiskey før',
    'Jeg har aldri klikka på noen i det offentlige',
    'Jeg har aldri stjelt noe fra en butikk',
    'Jeg har aldri snuset/røyket',
    'Jeg har aldri smakt sushi',
    'Jeg har aldri solgt min gamle mobil',
    'Jeg har aldri sett en jevnaldrende jente naken',
    'Jeg har aldri sett en jevnaldrende gutt naken',
    'Jeg har aldri sittet i et flyvende helikopter',
    'Jeg har aldri drukket meg full',
    'Jeg har aldri kjøpt en pc selv',
    'Jeg har aldri fått blackouts på fest',
    'Jeg har aldri lastet ned en piratkopiert film eller tvserie',
    'Jeg har aldri drukket alkohol',
    'Jeg har aldri sølt vann/flytende væske over min bærbare pc',
    'Jeg har aldri kjørt på et dyr',
    'Jeg har aldri kjørt vannscooter',
    'Jeg har aldri gjort på meg',
    'Jeg har aldri hatt sex',
    'Jeg har aldri utnytta en garanti',
    'Jeg har aldri sett en ordentlig brann',
    'Jeg har aldri vært noe spessielt slem',
    'Jeg har aldri vært frekk mot læreren',
    'Jeg har aldri kjøpt en Dvd film',
    'Jeg har aldri sett en ulv',
    'Jeg har aldri stått på ski',
    'Jeg har aldri spilt Bowling',
    'Jeg har aldri prøvd en mac-pc',
    'Jeg har aldri fått atferd-anmerkning',
    'Jeg har aldri vært den første som angriper noen',
    'Jeg har aldri spist så mye at jeg har spydd',
    'Jeg har aldri drukket abbsint',
    'Jeg har aldri slått ned noen',
    'Jeg har aldri vært våken i mer enn 3 døgn',
    'Jeg har aldri falt gjennom isen om vinteren',
    'Jeg har aldri vært på fest!',
    'Jeg har aldri sett noen dø',
    'Jeg har aldri bestillt noe fra utlandet',
    'Jeg har aldri spydd på noen andre',
    'Jeg har aldri vært på fylla over 3 dager på rad',
    'Jeg har aldri kysset en politimann/kvinne',
    'Jeg har aldri falt ned fra et tre',
    'Jeg har aldri smakt is med agurk smak før',
    'Jeg har aldri blitt tatt for å jukse på prøver',
    'Jeg har aldri jukset på prøver',
    'Jeg har aldri rømt hjemmfra',
    'Jeg har aldri tjent over 100 000 på et år',
]